import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles(() => ({
  inputSearch: {
    backgroundColor: '#fff',
    border: '1px solid #F7F7F7',
    borderRadius: '4px',
    fontSize: '14px !important',
    padding: '10px',
    height: '40px',
  },
  scanme: {
    textAlign: 'center',
    fontSize: '30px',
    color: '#fff',
    textTransform: 'uppercase',
    padding: '10px 80px',
    backgroundColor: '#000',
    borderRadius: '10px',
    fontWeight: 'bold',
    marginBottom: '32px',
    position: 'relative',
  },
  square: {
    content: '',
    width: '20px',
    height: '20px',
    backgroundColor: '#000',
    display: 'block',
    position: 'absolute',
    bottom: 0,
    left: '50%',
    transform: 'translate(-50%, 50%) rotate(-45deg)',
  },
  edge: {
    width: 20,
    height: 20,
    borderColor: '#000',
    zIndex: 2,
    position: 'absolute',
  },
  topLeft: {
    borderTop: '4px solid #000',
    borderLeft: '4px solid #000',
    borderTopLeftRadius: 4,
    top: -4,
    left: -4,
  },
  topRight: {
    borderRight: '4px solid #000',
    borderTop: '4px solid #000',
    borderTopRightRadius: 4,
    top: -4,
    right: -4,
  },
  bottomLeft: {
    borderBottom: '4px solid #000',
    borderLeft: '4px solid #000',
    borderBottomLeftRadius: 4,
    bottom: -4,
    left: -4,
  },
  bottomRight: {
    borderBottom: '4px solid #000',
    borderRight: '4px solid #000',
    borderBottomRightRadius: 4,
    bottom: -4,
    right: -2,
  },
}));
